"""add auth tables

Revision ID: 2026_03_08_001
Revises: 2026_03_03_001
Create Date: 2026-03-08 00:19:22.868992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_03_08_001'
down_revision: Union[str, Sequence[str], None] = '2026_03_03_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='learn_auth'
    )
    op.create_index(op.f('ix_learn_auth_users_email'), 'users', ['email'], unique=True, schema='learn_auth')
    op.create_index(op.f('ix_learn_auth_users_id'), 'users', ['id'], unique=False, schema='learn_auth')
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['learn_auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='learn_auth'
    )
    op.create_index(op.f('ix_learn_auth_email_verifications_id'), 'email_verifications', ['id'], unique=False, schema='learn_auth')
    op.create_index(op.f('ix_learn_auth_email_verifications_token_hash'), 'email_verifications', ['token_hash'], unique=True, schema='learn_auth')
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['learn_auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='learn_auth'
    )
    op.create_index(op.f('ix_learn_auth_password_resets_id'), 'password_resets', ['id'], unique=False, schema='learn_auth')
    op.create_index(op.f('ix_learn_auth_password_resets_token_hash'), 'password_resets', ['token_hash'], unique=True, schema='learn_auth')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('device_info', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['learn_auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='learn_auth'
    )
    op.create_index(op.f('ix_learn_auth_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False, schema='learn_auth')
    op.create_index(op.f('ix_learn_auth_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False, schema='learn_auth')
    op.create_index(op.f('ix_learn_auth_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True, schema='learn_auth')
    op.create_index(op.f('ix_learn_auth_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='learn_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learn_auth_refresh_tokens_user_id'), table_name='refresh_tokens', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_refresh_tokens_jti'), table_name='refresh_tokens', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_refresh_tokens_id'), table_name='refresh_tokens', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_refresh_tokens_family_id'), table_name='refresh_tokens', schema='learn_auth')
    op.drop_table('refresh_tokens', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_password_resets_token_hash'), table_name='password_resets', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_password_resets_id'), table_name='password_resets', schema='learn_auth')
    op.drop_table('password_resets', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_email_verifications_token_hash'), table_name='email_verifications', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_email_verifications_id'), table_name='email_verifications', schema='learn_auth')
    op.drop_table('email_verifications', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_users_id'), table_name='users', schema='learn_auth')
    op.drop_index(op.f('ix_learn_auth_users_email'), table_name='users', schema='learn_auth')
    op.drop_table('users', schema='learn_auth')
    # ### end Alembic commands ###
